### PR TITLE
Replace glyphicons with Iconicons

### PR DESCRIPTION
**Pull request by osqq**
Replace Glyphicons with iconicons, remove all glyphicon references and some little css changes to adjust the iconicons

### CODE REVIEW

**Comment by ZakarFin** [comment]
Can you remove all the icons that are not used and link the license for these icons?

**Comment by osqq** [comment]
All now removed, license at https://github.com/ionic-team/ionicons/blob/master/LICENSE , should it be included in the folder?

**Comment by ZakarFin** [comment]
Thanks! Based on "Replace glyphicons with Iconicons" I actually thought this was another lib since there's an additional `c` in there :D I think this is good for now 👍 I'll merge this on monday.

**Comment by osqq** [comment]
> Thanks! Based on "Replace glyphicons with Iconicons" I actually thought this was another lib since there's an additional `c` in there :D I think this is good for now 👍 I'll merge this on monday.

Ah no just my dyslexia 😄

**Pull request merged**
