### PR TITLE
jstree upgraded 3.3.5 -> 3.3.8

### PR DESCRIPTION
**Pull request by kuosman**
This upgrade fixes Chrome issue:
jstree.js:9743 [Deprecation] document.registerElement is deprecated and will be removed in M73, around March 2019. Please use window.customElements.define instead. See https://www.chromestatus.com/features/4642138092470272 for more details.

### CODE REVIEW

**Comment by ZakarFin** [comment]
Any chance to use this from npm? https://www.npmjs.com/package/jstree

**Comment by kuosman** [comment]
Ok, i check

**Comment by ZakarFin** [comment]
Might need to configure webpack/babel a bit: https://github.com/vakata/jstree/issues/1675

**Comment by kuosman** [comment]
babel-loader exlude not work, same jstree is not function error come

**Comment by kuosman** [comment]
and when added provideplugin (jQuery) come csrf token is null error and says Unable to start because of this (getappsetup action throw error)

--> Cannot use npm

**Comment by ZakarFin** [comment]
Ok, I guess we'll take another crack at npm libs when migrating to React.

**Pull request merged**
