### PR TITLE
Remove "old" hierarchical layerlist and admin functionalities

### PR DESCRIPTION
**Pull request by mr-lev1**
The "old" hierarchical layerlist along with its admin functionalities are removed since they will become obsolete when the hierarchical features of the new layerlist will be released.

### CODE REVIEW

**Comment by mr-lev1** [comment]
Maybe it would be best to instead replace the glyphicons anyway, as @ZakarFin has suggested.

**Comment by ZakarFin** [comment]
I'll craft some email to the mailing list about the bundles we want to remove after 2.2.0 and lets see if we get some responses to those.

**Comment by ZakarFin** [comment]
Added an issue for the clean up: oskariorg/oskari-docs#245 and email requesting action if these are to be kept in oskari-frontend

**Comment by ZakarFin** [comment]
These bundles have been removed in other pull requests so closing this one (for some reason it isn't closed automatically by GitHub).

**Pull request closed without merging**
